# Generated by Django 4.1.2 on 2022-10-07 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0002_alter_artist_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
